# Generated by Django 5.2.16 on 2026-07-28 21:27

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.accounts.models.avatar_path),
        ),
        migrations.CreateModel(
            name='SampleWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.accounts.models.sample_work_path)),
                ('title', models.CharField(max_length=120)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_works', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
