# Generated by Django 5.2.16 on 2026-07-28 22:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """Alters `volume` from FloatField(0..1) to PositiveSmallIntegerField(0..100).

    This cast is only safe because the `userpreferences` table is provably
    empty at every point this migration has run: no serializer, view, service,
    signal, or seed command has ever created a row (the model was orphaned
    until this change), so there is no existing 0.8-style value that would
    floor to 0 under the cast.
    """

    dependencies = [
        ('accounts', '0002_alter_user_avatar_samplework'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='playback_quality',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low')], default='high', max_length=4),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='repeat_mode',
            field=models.CharField(choices=[('off', 'Off'), ('all', 'All'), ('one', 'One')], default='off', max_length=4),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='shuffle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('es', 'Spanish')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='volume',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
