# Generated by Django 5.2.16 on 2026-07-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_add_avatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_view_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_stream_limit',
            field=models.IntegerField(blank=True, help_text='Null means unlimited', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_early_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='playlist_limit',
            field=models.IntegerField(blank=True, help_text='Null means unlimited', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('basic', 'Base (Free)'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=8, unique=True),
        ),
    ]
