# Generated by Django 5.2.17 on 2026-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='period_months',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (3, '3'), (6, '6'), (12, '12')], default=1),
        ),
    ]
