# Generated by Django 5.2.17 on 2026-08-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_transaction_period_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_add_avatar',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_download',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='can_view_stats',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='daily_stream_limit',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_early_access',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='playlist_limit',
        ),
    ]
