# Generated by Django 5.2.16 on 2026-07-28 21:27

import apps.playlists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.playlists.models.playlist_cover_path),
        ),
    ]
