# Generated by Django 5.2.16 on 2026-07-29 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('per_stream_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('per_listener_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_from', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ArtistPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.DateField(db_index=True)),
                ('unique_listeners', models.PositiveIntegerField()),
                ('streams', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=8)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_settled', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='reports.payoutpolicy')),
            ],
            options={
                'ordering': ['-period_month', 'artist_id'],
                'indexes': [models.Index(fields=['period_month', 'status'], name='reports_art_period__af0988_idx')],
                'constraints': [models.UniqueConstraint(fields=('artist', 'period_month'), name='uniq_artist_payout_period')],
            },
        ),
    ]
