# Generated by Django 5.2.16 on 2026-07-28 13:38

import apps.catalog.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.track_cover_path)),
                ('lyrics', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, db_index=True, max_length=40)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('released_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('album_track', 'Album track')], default='single', max_length=16)),
                ('collaborators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None)),
                ('audio_high', models.FileField(blank=True, null=True, upload_to=apps.catalog.models.track_audio_path)),
                ('audio_low', models.FileField(blank=True, null=True, upload_to=apps.catalog.models.track_audio_path)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('early_access_until', models.DateTimeField(blank=True, null=True)),
                ('play_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('unique_listener_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.album_cover_path)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('released_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
