# Generated by Django 5.2.16 on 2026-07-28 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playevent',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_events', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playevent',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='catalog.track'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', '-released_at'], name='catalog_alb_artist__13ab03_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist', '-released_at'], name='catalog_tra_artist__e5e534_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['genre'], name='catalog_tra_genre_25eae7_idx'),
        ),
        migrations.AddIndex(
            model_name='playevent',
            index=models.Index(fields=['user', '-played_at'], name='catalog_pla_user_id_b85a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='playevent',
            index=models.Index(fields=['track', '-played_at'], name='catalog_pla_track_i_3762e9_idx'),
        ),
        migrations.AddIndex(
            model_name='playevent',
            index=models.Index(fields=['user', 'track'], name='catalog_pla_user_id_18d22e_idx'),
        ),
    ]
