# Generated by Django 5.2.16 on 2026-07-28 21:27

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.catalog.models.album_cover_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_high',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.catalog.models.track_audio_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_low',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.catalog.models.track_audio_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.catalog.models.track_cover_path),
        ),
    ]
